nationalities = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo Republic",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "DR Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyz Republic",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia, Fed. Sts.",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "St. Kitts and Nevis",
    "St. Lucia",
    "St. Vincent and the Grenadines",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkmenistan",
    "Tuvalu",
    "Türkiye",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

nationalities_es = [
    "Afganistán",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua y Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaiyán",
    "Bahamas",
    "Baréin",
    "Bangladés",
    "Barbados",
    "Bielorrusia",
    "Bélgica",
    "Belice",
    "Benín",
    "Bután",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunei Darussalam",
    "Bulgaria",
    "Burquina Faso",
    "Burundi",
    "Cabo Verde",
    "Camboya",
    "Camerún",
    "Canadá",
    "República Centroafricana",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comores, Islas",
    "Congo",
    "Costa Rica",
    "Costa de Marfíl",
    "Croacia",
    "Cuba",
    "Chipre",
    "Chequia",
    "Congo, República Democrática del",
    "Dinamarca",
    "Yibuti",
    "Dominica",
    "República Dominicana",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Guinea Ecuatorial",
    "Eritrea",
    "Estonia",
    "Esuatini",
    "Etiopía",
    "Fiyi",
    "Finlandia",
    "Francia",
    "Gabón",
    "Gambia",
    "Georgia",
    "Alemania",
    "Ghana",
    "Grecia",
    "Granada",
    "Guatemala",
    "Guinea",
    "Guinea-Bisáu",
    "Guyana",
    "Haití",
    "Honduras",
    "Hungría",
    "Islandia",
    "India",
    "Indonesia",
    "Irán",
    "Irak",
    "Irlanda",
    "Israel",
    "Italia",
    "Jamaica",
    "Japón",
    "Jordania",
    "Kazajistán",
    "Kenia",
    "Kiribati",
    "Kuwait",
    "Kirguistán",
    "Laos",
    "Letonia",
    "Líbano",
    "Lesoto",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Madagascar",
    "Malaui",
    "Malasia",
    "Islas Maldivas",
    "Malí",
    "Malta",
    "Islas Marshall",
    "Mauritania",
    "Mauricio",
    "México",
    "Micronesia, Estados Federados de",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Marruecos",
    "Mozambique",
    "Birmania",
    "Namibia",
    "Nauru",
    "Nepal",
    "Países Bajos",
    "Nueva Zelanda",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Corea del Norte",
    "Macedonia del Norte",
    "Noruega",
    "Omán",
    "Pakistán",
    "Palaos",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Perú",
    "Filipinas",
    "Polonia",
    "Portugal",
    "Catar",
    "Rumanía",
    "Rusia",
    "Ruanda",
    "Samoa",
    "San Marino",
    "Santo Tomé y Príncipe",
    "Arabia Saudí",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leona",
    "Singapur",
    "Eslovaquia",
    "Eslovenia",
    "Islas Salomón",
    "Somalia",
    "Sudáfrica",
    "Corea del Sur",
    "Sudán del Sur",
    "España",
    "Sri Lanka",
    "San Cristóbal y Nieves",
    "Santa Lucía",
    "San Vicente y las Granadinas",
    "Sudán",
    "Surinám",
    "Suecia",
    "Suiza",
    "Siria",
    "Tayikistán",
    "Tanzania",
    "Tailandia",
    "Timor Oriental",
    "Togo",
    "Tonga",
    "Trinidad y Tobago",
    "Tunez",
    "Turkmenistán",
    "Tuvalu",
    "Turquía",
    "Uganda",
    "Ucrania",
    "Emiratos Árabes Unidos",
    "Reino Unido",
    "Estados Unidos",
    "Uruguay",
    "Uzbekistán",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabue",
]

nationalities_pt = [
    "Afeganistão",
    "Albânia",
    "Argélia",
    "Andorra",
    "Angola",
    "Antígua e Barbuda",
    "Argentina",
    "Arménia",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahamas",
    "Barém",
    "Bangladeche",
    "Barbados",
    "Bielorússia",
    "Bélgica",
    "Belize",
    "Benim",
    "Butão",
    "Bolívia",
    "Bósnia e Herzegovina",
    "Botsuana",
    "Brasil",
    "Brunei",
    "Bulgária",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Camboja",
    "Camarões",
    "Canadá",
    "República Centro-Africana",
    "Chade",
    "Chile",
    "China",
    "Colômbia",
    "Comores",
    "Congo",
    "Costa Rica",
    "Costa do Marfim",
    "Croácia",
    "Cuba",
    "Chipre",
    "Chéquia",
    "Congo, República Democrática do",
    "Dinamarca",
    "Djibouti",
    "Dominica",
    "República Dominicana",
    "Equador",
    "Egito",
    "El Salvador",
    "Guiné Equatorial",
    "Eritreia",
    "Estónia",
    "Suazilândia",
    "Etiópia",
    "Fiji",
    "Finlândia",
    "França",
    "Gabão",
    "Gâmbia",
    "Geórgia",
    "Alemanha",
    "Gana",
    "Grécia",
    "Granada",
    "Guatemala",
    "Guiné",
    "Guiné-Bissáu",
    "Guiana",
    "Haiti",
    "Honduras",
    "Hungria",
    "Islândia",
    "Índia",
    "Indonésia",
    "Iran",
    "Iraque",
    "Irlanda",
    "Israel",
    "Itália",
    "Jamaica",
    "Japão",
    "Jordânia",
    "Cazaquistão",
    "Quénia",
    "Kiribati",
    "Kuwait",
    "Quirguistão",
    "Laos",
    "Letónia",
    "Líbano",
    "Lesoto",
    "Libéria",
    "Líbia",
    "Liechtenstein",
    "Lituânia",
    "Luxemburgo",
    "Madagáscar",
    "Malawi",
    "Malásia",
    "Maldivas",
    "Mali",
    "Malta",
    "Ilhas Marshall",
    "Mauritânia",
    "Maurícia",
    "México",
    "Micronésia, Estados Federados da",
    "Moldávia",
    "Mónaco",
    "Mongólia",
    "Montenegro",
    "Marrocos",
    "Moçambique",
    "Birmânia",
    "Namíbia",
    "Nauru",
    "Nepal",
    "Países Baixos",
    "Nova Zelândia",
    "Nicarágua",
    "Níger",
    "Nigéria",
    "Coreia do Norte",
    "Macedónia do Norte",
    "Noruega",
    "Omã",
    "Paquistão",
    "Palau",
    "Panamá",
    "Papua Nova Guiné",
    "Paraguai",
    "Peru",
    "Filipinas",
    "Polónia",
    "Portugal",
    "Catar",
    "Roménia",
    "Rússia",
    "Ruanda",
    "Samoa",
    "San Marino",
    "São Tomé e Príncipe",
    "Arábia Saudita",
    "Senegal",
    "Sérvia",
    "Seychelles",
    "Serra Leoa",
    "Singapura",
    "Eslováquia",
    "Eslovénia",
    "Ilhas Salomão",
    "Somália",
    "África do Sul",
    "Coreia do Sul",
    "Sudão do Sul",
    "Espanha",
    "Sri Lanka",
    "São Cristóvão e Nevis",
    "Santa Lúcia",
    "São Vicente e Granadinas",
    "Sudão",
    "Suriname",
    "Suécia",
    "Suíça",
    "Syria",
    "Tajiquistão",
    "Tanzânia",
    "Tailândia",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trindade e Tobago",
    "Tunísia",
    "Turquemenistão",
    "Tuvalu",
    "Turquia",
    "Uganda",
    "Ucrânia",
    "Emirados Árabes Unidos",
    "Reino Unido",
    "Estados Unidos",
    "Uruguai",
    "Uzbequistão",
    "Vanuatu",
    "Venezuela",
    "Vietname",
    "Iémen",
    "Zâmbia",
    "Zimbábue",
]

translated_nationalities = {
    "es": dict(zip(nationalities, nationalities_es)),
    "pt": dict(zip(nationalities, nationalities_pt)),
    "en": dict(zip(nationalities, nationalities)),
}
